### ISSUE TITLE
incompatible with cold sweat and Mekanism

### ISSUE THREAD

**Issue by codec-d** [VeroxUniverse/EpicEmpires-NeoForge#1]
in singleplayer testing I got this with an armor stand and refined glowstone chest armor: https://pastebin.com/XF1N1mhz

on a server i got this when attempting to render in 3rd person: https://pastebin.com/wW5Lnj03

when attempting to view in jei I get the following from the log:: [oshi.util.FileUtil/]: No oshi.architecture.properties file found from ClassLoader cpw.mods.modlauncher.TransformingClassLoader@289da1bc

finally figured it out when I saw this::

at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_117118_(HumanoidArmorLayer.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23914!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelibarmor.mixins.json:MixinHumanoidArmorLayer,pl:mixin:APP:immersive_armors.mixins.json:MixinArmorFeatureRenderer,pl:mixin:APP:doapi-common.mixins.json:armor.ArmorFeatureRendererMixin,pl:mixin:APP:tenshilib.mixins.json:HumanoidArmorMixin,pl:mixin:APP:werewolves.mixins.json:client.HumanoidArmorLayerMixin,pl:mixin:APP:playerAnimator-common.mixins.json:ArmorFeatureRendererMixin,pl:mixin:APP:nyfsquiver.mixins.json:HumanoidArmorLayerMixin,pl:mixin:APP:create.mixins.json:client.HumanoidArmorLayerMixin,pl:mixin:APP:create.mixins.json:accessor.HumanoidArmorLayerAccessor,pl:mixin:APP:structure_gel.mixins.json:ArmorTrimMixins$HumanoidArmorLayerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.entity.layers.HumanoidArmorLayer.m_6494_(HumanoidArmorLayer.java:44) ~[client-1.20.1-20230612.114412-srg.jar%23914!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:azurelibarmor.mixins.json:MixinHumanoidArmorLayer,pl:mixin:APP:immersive_armors.mixins.json:MixinArmorFeatureRenderer,pl:mixin:APP:doapi-common.mixins.json:armor.ArmorFeatureRendererMixin,pl:mixin:APP:tenshilib.mixins.json:HumanoidArmorMixin,pl:mixin:APP:werewolves.mixins.json:client.HumanoidArmorLayerMixin,pl:mixin:APP:playerAnimator-common.mixins.json:ArmorFeatureRendererMixin,pl:mixin:APP:nyfsquiver.mixins.json:HumanoidArmorLayerMixin,pl:mixin:APP:create.mixins.json:client.HumanoidArmorLayerMixin,pl:mixin:APP:create.mixins.json:accessor.HumanoidArmorLayerAccessor,pl:mixin:APP:structure_gel.mixins.json:ArmorTrimMixins$HumanoidArmorLayerMixin,pl:mixin:A,pl:runtimedistcleaner:A}

**Comment by VeroxUniverse** [comment]
I think that Issue is not caused by EpicEmpires. I still happens if I remove EpicEmpires. I think it is caused by Azurelib Armor. I would recommend to report it to AzureDoom. Or maybe to the Mekanism team.

**Comment by VeroxUniverse** [comment]
Try using version 0.0.1 of EpicEmpires with version 1.0.3 of AzureLib Armor
